# Generated by Django 4.2.4 on 2023-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
