# Generated by Django 4.2.4 on 2023-09-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='fin_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
